---
# =============================================================================
# Play 1: Remove user-ca-bundle from all clusters
# =============================================================================
- name: Remove user-ca-bundle SSL configuration from all clusters
  hosts: openshift_clusters
  gather_facts: false

  vars:
    artifacts_dir: "{{ playbook_dir }}/artifacts"

  pre_tasks:
    - name: Skip non-hub clusters
      meta: end_host
      when: cluster_role | default('spoke') != 'hub'

    - name: Validate kubeconfig exists
      stat:
        path: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      register: kubeconfig_stat
      delegate_to: localhost

    - name: Skip if kubeconfig missing
      meta: end_host
      when: not kubeconfig_stat.stat.exists

    - name: Build list of spoke clusters
      set_fact:
        spoke_clusters: >-
          {{ groups['openshift_clusters']
             | map('extract', hostvars)
             | selectattr('cluster_role', 'defined')
             | selectattr('cluster_role', 'equalto', 'spoke')
             | map(attribute='cluster_name')
             | list
          + groups['openshift_clusters']
             | map('extract', hostvars)
             | rejectattr('cluster_role', 'defined')
             | map(attribute='cluster_name')
             | list }}

  tasks:
    - name: Remove trustedCA from proxy on hub cluster
      shell: |
        oc patch proxy cluster --type=merge \
          --patch='{"spec":{"trustedCA":{"name":""}}}'
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      ignore_errors: true

    - name: Remove trustedCA from proxy on spoke clusters
      shell: |
        oc patch proxy cluster --type=merge \
          --patch='{"spec":{"trustedCA":{"name":""}}}'
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ item }}/kubeconfig"
      delegate_to: localhost
      loop: "{{ spoke_clusters }}"
      ignore_errors: true

    - name: Delete user-ca-bundle configmap from hub cluster
      shell: |
        oc delete configmap user-ca-bundle -n openshift-config --ignore-not-found
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      ignore_errors: true

    - name: Delete user-ca-bundle configmap from spoke clusters
      shell: |
        oc delete configmap user-ca-bundle -n openshift-config --ignore-not-found
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ item }}/kubeconfig"
      delegate_to: localhost
      loop: "{{ spoke_clusters }}"
      ignore_errors: true

    - name: Display user-ca-bundle removal result
      debug:
        msg: "Removed user-ca-bundle and proxy trustedCA from all clusters"

# =============================================================================
# Play 2: Remove StorageCluster and ODF from spoke clusters
# =============================================================================
- name: Remove StorageCluster and ODF from spoke clusters
  hosts: openshift_clusters
  gather_facts: false

  vars:
    artifacts_dir: "{{ playbook_dir }}/artifacts"

  pre_tasks:
    - name: Skip non-spoke clusters
      meta: end_host
      when: cluster_role | default('spoke') != 'spoke'

    - name: Validate kubeconfig exists
      stat:
        path: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      register: kubeconfig_stat
      delegate_to: localhost

    - name: Skip if kubeconfig missing
      meta: end_host
      when: not kubeconfig_stat.stat.exists

  tasks:
    # =========================================================================
    # Delete StorageCluster (no wait, then handle finalizers)
    # =========================================================================
    - name: Delete StorageCluster (no wait)
      shell: |
        oc delete storagecluster ocs-storagecluster -n openshift-storage --ignore-not-found --wait=false
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      ignore_errors: true

    - name: Remove finalizers from StorageCluster if stuck
      shell: |
        for cr in $(oc get storagecluster -n openshift-storage -o name 2>/dev/null); do
          oc patch "$cr" -n openshift-storage --type=merge -p '{"metadata":{"finalizers":[]}}' 2>/dev/null || true
        done
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      ignore_errors: true

    - name: Wait for StorageCluster removal
      shell: |
        oc get storagecluster -n openshift-storage 2>&1 | grep -qE "No resources|not found" && echo "deleted" || echo "pending"
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      register: sc_check
      until: '"deleted" in sc_check.stdout'
      retries: 30
      delay: 10
      changed_when: false
      ignore_errors: true

    # =========================================================================
    # Clean up CephCluster sub-resources that may block namespace deletion
    # =========================================================================
    - name: Delete CephCluster resources (no wait)
      shell: |
        oc delete cephcluster --all -n openshift-storage --ignore-not-found --wait=false 2>/dev/null || true
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      ignore_errors: true

    - name: Remove finalizers from CephCluster if stuck
      shell: |
        for cr in $(oc get cephcluster -n openshift-storage -o name 2>/dev/null); do
          oc patch "$cr" -n openshift-storage --type=merge -p '{"metadata":{"finalizers":[]}}' 2>/dev/null || true
        done
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      ignore_errors: true

    # =========================================================================
    # Remove ODF operator
    # =========================================================================
    - name: Remove ODF storage labels from worker nodes
      shell: |
        oc label nodes -l cluster.ocs.openshift.io/openshift-storage \
          cluster.ocs.openshift.io/openshift-storage- --ignore-not-found
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      ignore_errors: true

    - name: Delete ODF Operator Subscription
      shell: |
        oc delete subscription odf-operator -n openshift-storage --ignore-not-found
        oc delete subscription ocs-operator -n openshift-storage --ignore-not-found
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      ignore_errors: true

    - name: Delete all ClusterServiceVersions in openshift-storage
      shell: |
        oc delete csv --all -n openshift-storage --ignore-not-found
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      ignore_errors: true

    - name: Delete ODF OperatorGroup
      shell: |
        oc delete operatorgroup openshift-storage-operatorgroup -n openshift-storage --ignore-not-found
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      ignore_errors: true

    # =========================================================================
    # Delete openshift-storage namespace
    # =========================================================================
    - name: Delete openshift-storage namespace
      shell: |
        oc delete namespace openshift-storage --ignore-not-found --timeout=120s
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      ignore_errors: true

    - name: Force-clear finalizers on stuck resources in openshift-storage namespace
      shell: |
        NS_PHASE=$(oc get namespace openshift-storage -o jsonpath='{.status.phase}' 2>/dev/null || echo "")
        if [ "$NS_PHASE" = "Terminating" ]; then
          for resource in $(oc api-resources --verbs=list --namespaced -o name 2>/dev/null); do
            for item in $(oc get "$resource" -n openshift-storage -o name 2>/dev/null); do
              oc patch "$item" -n openshift-storage --type=merge -p '{"metadata":{"finalizers":[]}}' 2>/dev/null || true
            done
          done
        fi
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      ignore_errors: true

    - name: Wait for openshift-storage namespace deletion
      shell: |
        oc get namespace openshift-storage 2>&1 | grep -q "not found" && echo "deleted" || echo "pending"
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      register: ns_delete_check
      until: '"deleted" in ns_delete_check.stdout'
      retries: 20
      delay: 10
      changed_when: false
      ignore_errors: true

    - name: Display ODF removal result
      debug:
        msg: |
          ============================================
          ODF StorageCluster Removed
          ============================================
          Cluster: {{ cluster_name }}
          Removed: StorageCluster, ODF Operator, openshift-storage namespace

# =============================================================================
# Play 3: Remove Submariner networking
# =============================================================================
- name: Remove Submariner networking
  hosts: openshift_clusters
  gather_facts: false

  vars:
    artifacts_dir: "{{ playbook_dir }}/artifacts"

  pre_tasks:
    - name: Skip non-hub clusters
      meta: end_host
      when: cluster_role | default('spoke') != 'hub'

    - name: Validate kubeconfig exists
      stat:
        path: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      register: kubeconfig_stat
      delegate_to: localhost

    - name: Fail if kubeconfig missing
      fail:
        msg: "Kubeconfig not found at {{ artifacts_dir }}/{{ cluster_name }}/kubeconfig."
      when: not kubeconfig_stat.stat.exists

    - name: Build list of spoke clusters
      set_fact:
        spoke_clusters: >-
          {{ groups['openshift_clusters']
             | map('extract', hostvars)
             | selectattr('cluster_role', 'defined')
             | selectattr('cluster_role', 'equalto', 'spoke')
             | map(attribute='cluster_name')
             | list
          + groups['openshift_clusters']
             | map('extract', hostvars)
             | rejectattr('cluster_role', 'defined')
             | map(attribute='cluster_name')
             | list }}

    - name: Build list of all managed clusters
      set_fact:
        all_managed_clusters: "{{ ['local-cluster'] + spoke_clusters }}"

  tasks:
    # =========================================================================
    # Delete Submariner ManagedClusterAddOn (no wait, then handle finalizers)
    # =========================================================================
    - name: Delete Submariner ManagedClusterAddOn (no wait)
      shell: |
        oc delete managedclusteraddon submariner -n {{ item }} --ignore-not-found --wait=false
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      loop: "{{ all_managed_clusters }}"
      ignore_errors: true

    - name: Remove finalizers from Submariner ManagedClusterAddOn if stuck
      shell: |
        oc patch managedclusteraddon submariner -n {{ item }} --type=merge \
          -p '{"metadata":{"finalizers":[]}}' 2>/dev/null || true
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      loop: "{{ all_managed_clusters }}"
      ignore_errors: true

    - name: Wait for ManagedClusterAddOn deletion
      shell: |
        oc get managedclusteraddon submariner -n {{ item }} 2>&1 | grep -q "not found" && echo "deleted" || echo "pending"
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      register: addon_delete_check
      until: '"deleted" in addon_delete_check.stdout'
      retries: 18
      delay: 10
      changed_when: false
      loop: "{{ all_managed_clusters }}"
      ignore_errors: true

    # =========================================================================
    # Delete SubmarinerConfig (no wait, then handle finalizers)
    # =========================================================================
    - name: Delete SubmarinerConfig (no wait)
      shell: |
        oc delete submarinerconfig submariner -n {{ item }} --ignore-not-found --wait=false
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      loop: "{{ all_managed_clusters }}"
      ignore_errors: true

    - name: Remove finalizers from SubmarinerConfig if stuck
      shell: |
        oc patch submarinerconfig submariner -n {{ item }} --type=merge \
          -p '{"metadata":{"finalizers":[]}}' 2>/dev/null || true
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      loop: "{{ all_managed_clusters }}"
      ignore_errors: true

    - name: Wait for SubmarinerConfig deletion
      shell: |
        oc get submarinerconfig submariner -n {{ item }} 2>&1 | grep -q "not found" && echo "deleted" || echo "pending"
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      register: smconfig_delete_check
      until: '"deleted" in smconfig_delete_check.stdout'
      retries: 18
      delay: 10
      changed_when: false
      loop: "{{ all_managed_clusters }}"
      ignore_errors: true

    # =========================================================================
    # Clean up remaining Submariner resources
    # =========================================================================
    - name: Delete Submariner AWS credentials secrets
      shell: |
        oc delete secret {{ item }}-aws-creds -n {{ item }} --ignore-not-found
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      loop: "{{ all_managed_clusters }}"
      ignore_errors: true

    - name: Remove clusterset labels from managed clusters
      shell: |
        oc label managedcluster {{ item }} cluster.open-cluster-management.io/clusterset- --ignore-not-found
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      loop: "{{ all_managed_clusters }}"
      ignore_errors: true

    - name: Delete ManagedClusterSetBinding
      shell: |
        oc delete managedclustersetbinding {{ managed_cluster_set_name }} -n open-cluster-management --ignore-not-found
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      ignore_errors: true

    # =========================================================================
    # Delete Submariner Broker and broker namespace
    # =========================================================================
    - name: Delete Submariner Broker (no wait)
      shell: |
        oc delete broker submariner-broker -n {{ managed_cluster_set_name }}-broker --ignore-not-found --wait=false
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      ignore_errors: true

    - name: Remove finalizers from Submariner Broker if stuck
      shell: |
        oc patch broker submariner-broker -n {{ managed_cluster_set_name }}-broker --type=merge \
          -p '{"metadata":{"finalizers":[]}}' 2>/dev/null || true
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      ignore_errors: true

    - name: Delete broker namespace
      shell: |
        oc delete namespace {{ managed_cluster_set_name }}-broker --ignore-not-found --timeout=120s
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      ignore_errors: true

    - name: Force-clear finalizers on stuck resources in broker namespace
      shell: |
        NS_PHASE=$(oc get namespace {{ managed_cluster_set_name }}-broker -o jsonpath='{.status.phase}' 2>/dev/null || echo "")
        if [ "$NS_PHASE" = "Terminating" ]; then
          for resource in $(oc api-resources --verbs=list --namespaced -o name 2>/dev/null); do
            for item in $(oc get "$resource" -n {{ managed_cluster_set_name }}-broker -o name 2>/dev/null); do
              oc patch "$item" -n {{ managed_cluster_set_name }}-broker --type=merge -p '{"metadata":{"finalizers":[]}}' 2>/dev/null || true
            done
          done
        fi
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      ignore_errors: true

    - name: Wait for broker namespace deletion
      shell: |
        oc get namespace {{ managed_cluster_set_name }}-broker 2>&1 | grep -q "not found" && echo "deleted" || echo "pending"
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      register: broker_ns_check
      until: '"deleted" in broker_ns_check.stdout'
      retries: 20
      delay: 10
      changed_when: false
      ignore_errors: true

    # =========================================================================
    # Delete ManagedClusterSet
    # =========================================================================
    - name: Delete ManagedClusterSet
      shell: |
        oc delete managedclusterset {{ managed_cluster_set_name }} --ignore-not-found
      environment:
        KUBECONFIG: "{{ artifacts_dir }}/{{ cluster_name }}/kubeconfig"
      delegate_to: localhost
      ignore_errors: true

    - name: Display Submariner removal result
      debug:
        msg: "Submariner networking and globalnet removed from cluster set {{ managed_cluster_set_name }}"
